import {
	type Action,
	ActionType,
	type Card,
	type Observation,
	cardStrength,
	isManilha,
} from "@trucobench/engine";
import type { Agent } from "./base-agent.ts";

/**
 * Heuristic agent with realistic bluffing, bluff detection, and score-aware play.
 *
 * Bluff probability is tuned so the agent:
 * - Bluffs more when behind on score
 * - Bluffs after winning trick 1 (positional advantage)
 * - Detects opponent bluffs based on score and stakes
 * - Varies responses to avoid being predictable
 */
const HEURISTIC_PHRASES = {
	truco: ["Pode vir!", "Tenho bala na agulha!", "Aceita se for corajoso!"],
	bluff_truco: ["Zap na mão!", "Você não faz ideia...", "Corre que é melhor!"],
	accept: ["Pode vir!", "É nossa, parceiro!"],
	fold_taunt: ["Tá com medo?", "Correu!"],
	win_trick: ["Toma!", "Fácil demais!", "Guardou pra quê?"],
	react: ["Eita!", "Opa!", "Sorte sua!"],
};

export class HeuristicAgent implements Agent {
	readonly name = "heuristic";

	/** Last chat message generated by this agent */
	lastChat: string | null = null;

	/** Seeded simple RNG for reproducible bluff decisions */
	private rngState: number;

	constructor(seed?: number) {
		this.rngState = seed ?? Math.floor(Math.random() * 2147483647);
	}

	/** Returns a value in [0, 1) */
	private random(): number {
		// Simple LCG — fast and deterministic
		this.rngState = (this.rngState * 1664525 + 1013904223) & 0x7fffffff;
		return this.rngState / 0x7fffffff;
	}

	async getAction(observation: Observation): Promise<Action> {
		const { hand, vira, legalActions, currentTrick, escalation, tricks, score, playerId } =
			observation;
		const oppIdx = playerId === 0 ? 1 : 0;
		const myScore = score[playerId]!;
		const oppScore = score[oppIdx]!;

		// Signal intelligence: assess team strength from partner/opponent signals
		const partnerStrong = this.assessPartnerStrength(observation.partnerSignals);
		const opponentStrong = this.assessOpponentStrength(observation.interceptedSignals);

		// --- Mao de onze decision ---
		if (observation.maoDeOnze) {
			const maoAction = this.decideMaoDeOnze(hand, vira, oppScore, partnerStrong);
			this.lastChat = this.generateChat(maoAction);
			return maoAction;
		}

		// --- Respond to escalation (with bluff detection + signal intel) ---
		if (escalation.pendingRequest !== null && escalation.requestedBy !== playerId) {
			const escAction = this.respondToEscalation(
				hand,
				vira,
				legalActions,
				tricks,
				myScore,
				oppScore,
				partnerStrong,
				opponentStrong,
			);
			this.lastChat = this.generateChat(escAction);
			return escAction;
		}

		// --- Initiate escalation (with bluffing + signal intel) ---
		const canTruco = legalActions.some((a) => a.type === ActionType.TRUCO);
		if (
			canTruco &&
			this.shouldCallTruco(hand, vira, tricks, myScore, oppScore, partnerStrong, opponentStrong)
		) {
			const trucoAction: Action = { type: ActionType.TRUCO };
			this.lastChat = this.generateChat(trucoAction);
			return trucoAction;
		}

		// --- Play a card ---
		const cardAction = this.chooseCard(hand, vira, legalActions, currentTrick, tricks.length);
		this.lastChat = this.generateChat(cardAction);
		return cardAction;
	}

	/** Generate contextual trash talk based on the action. Only ~30% of turns to avoid spam. */
	private generateChat(action: Action): string | null {
		if (this.random() > 0.3) return null; // 70% silent
		const pick = (arr: string[]) => arr[Math.floor(this.random() * arr.length)]!;
		switch (action.type) {
			case ActionType.TRUCO:
				return pick(this.random() < 0.5 ? HEURISTIC_PHRASES.truco : HEURISTIC_PHRASES.bluff_truco);
			case ActionType.ACCEPT:
				return pick(HEURISTIC_PHRASES.accept);
			case ActionType.FOLD:
				return null; // Don't trash talk when folding
			default:
				return pick(HEURISTIC_PHRASES.react);
		}
	}

	/* ── Signal assessment ──────────────────────────────── */

	/**
	 * Assess partner's hand strength from received signals.
	 * Returns a score: 0 = no info, 1 = weak, 2 = decent, 3 = strong.
	 */
	private assessPartnerStrength(signals?: { type: string; fromSeat: number }[]): number {
		if (!signals || signals.length === 0) return 0;
		let best = 0;
		for (const s of signals) {
			if (s.type === "ZAP") best = Math.max(best, 3);
			else if (s.type === "COPAS" || s.type === "ESPADAS") best = Math.max(best, 3);
			else if (s.type === "OUROS" || s.type === "THREE") best = Math.max(best, 2);
			else if (s.type === "TWO" || s.type === "ACE") best = Math.max(best, 1);
			else if (s.type === "NOTHING") best = Math.max(best, -1);
		}
		return best;
	}

	/**
	 * Assess opponent's hand strength from intercepted signals.
	 * Returns a score: 0 = no info, 1 = weak, 2 = decent, 3 = strong.
	 */
	private assessOpponentStrength(signals?: { type: string; fromSeat: number }[]): number {
		if (!signals || signals.length === 0) return 0;
		let best = 0;
		for (const s of signals) {
			if (s.type === "ZAP" || s.type === "COPAS" || s.type === "ESPADAS") best = Math.max(best, 3);
			else if (s.type === "OUROS" || s.type === "THREE") best = Math.max(best, 2);
			else if (s.type === "TWO" || s.type === "ACE") best = Math.max(best, 1);
			else if (s.type === "NOTHING") return -1; // Confirmed weak — exploit this
		}
		return best;
	}

	/* ── Mao de onze ───────────────────────────────────── */

	private decideMaoDeOnze(
		hand: Card[],
		vira: Card,
		oppScore: number,
		partnerStrong: number,
	): Action {
		const manilhaCount = hand.filter((c) => isManilha(c, vira)).length;
		const highCards = hand.filter((c) => cardStrength(c, vira) >= 7).length;

		// Always play with 1+ manilha or 2+ high cards
		if (manilhaCount >= 1 || highCards >= 2) {
			return { type: ActionType.ACCEPT };
		}
		// Partner signaled strong hand — trust the team
		if (partnerStrong >= 2 && highCards >= 1) {
			return { type: ActionType.ACCEPT };
		}
		// If opponent is also close (10+), take the risk more often
		if (oppScore >= 10 && highCards >= 1 && this.random() < 0.5) {
			return { type: ActionType.ACCEPT };
		}
		return { type: ActionType.FOLD };
	}

	/* ── Respond to escalation (bluff detection) ──────── */

	private respondToEscalation(
		hand: Card[],
		vira: Card,
		legalActions: Action[],
		tricks: Observation["tricks"],
		myScore: number,
		oppScore: number,
		partnerStrong: number,
		opponentStrong: number,
	): Action {
		const manilhaCount = hand.filter((c) => isManilha(c, vira)).length;
		const highCards = hand.filter((c) => cardStrength(c, vira) >= 7).length;
		const handStrengthScore = manilhaCount * 3 + highCards;

		// Estimate probability the opponent is bluffing
		let bluffLikelihood = this.estimateOpponentBluff(tricks, myScore, oppScore);

		// Signal intelligence adjustments
		// We intercepted opponent signal showing NOTHING → they're very likely bluffing!
		if (opponentStrong < 0) bluffLikelihood += 0.3;
		// We intercepted signal showing opponent is strong → less likely bluffing
		if (opponentStrong >= 3) bluffLikelihood -= 0.3;
		bluffLikelihood = Math.max(0, Math.min(1, bluffLikelihood));

		// Strong hand: always raise or accept
		if (manilhaCount >= 2) {
			if (legalActions.some((a) => a.type === ActionType.RAISE)) {
				return { type: ActionType.RAISE };
			}
			return { type: ActionType.ACCEPT };
		}

		// Decent hand: accept
		if (manilhaCount >= 1 || highCards >= 2) {
			// With a decent hand + opponent likely bluffing → raise to punish
			if (
				bluffLikelihood > 0.6 &&
				manilhaCount >= 1 &&
				legalActions.some((a) => a.type === ActionType.RAISE)
			) {
				return { type: ActionType.RAISE };
			}
			return { type: ActionType.ACCEPT };
		}

		// Team assessment: weak hand but partner signaled strong → accept, trust the team
		if (partnerStrong >= 2 && this.random() < 0.6) {
			return { type: ActionType.ACCEPT };
		}

		// Weak hand: fold/accept decision based on bluff detection
		if (bluffLikelihood > 0.7 && this.random() < 0.5) {
			return { type: ActionType.ACCEPT };
		}

		// Weak hand, opponent probably not bluffing, but if we're behind, take more risks
		if (oppScore >= myScore + 4 && handStrengthScore >= 1 && this.random() < 0.35) {
			return { type: ActionType.ACCEPT };
		}

		return { type: ActionType.FOLD };
	}

	/**
	 * Estimate how likely the opponent is bluffing (0 = surely strong, 1 = surely bluffing).
	 * Based on game-theoretic tells that real Truco players use.
	 */
	private estimateOpponentBluff(
		tricks: Observation["tricks"],
		myScore: number,
		oppScore: number,
	): number {
		let bluffScore = 0.3; // Base: 30% assumed bluff rate

		// Opponent losing → more likely to bluff
		if (myScore > oppScore + 3) bluffScore += 0.2;
		if (myScore > oppScore + 6) bluffScore += 0.15;

		// Opponent winning → less likely to bluff (why risk it?)
		if (oppScore > myScore + 3) bluffScore -= 0.15;

		// If opponent lost trick 1 and then called truco → classic bluff pattern
		if (tricks.length >= 1 && tricks[0]!.winner !== null) {
			const oppLostTrick1 = tricks[0]!.winner !== (myScore > oppScore ? 1 : 0); // rough heuristic
			if (oppLostTrick1) bluffScore += 0.2;
		}

		// If no tricks played yet (truco on first action) → moderate bluff likelihood
		if (tricks.length === 0) bluffScore += 0.1;

		return Math.max(0, Math.min(1, bluffScore));
	}

	/* ── Initiate escalation (bluffing) ───────────────── */

	private shouldCallTruco(
		hand: Card[],
		vira: Card,
		tricks: Observation["tricks"],
		myScore: number,
		oppScore: number,
		partnerStrong: number,
		opponentStrong: number,
	): boolean {
		const manilhaCount = hand.filter((c) => isManilha(c, vira)).length;
		const highCards = hand.filter((c) => cardStrength(c, vira) >= 7).length;

		// If we intercepted that opponent has strong cards → don't bluff
		if (opponentStrong >= 3 && manilhaCount < 2) return false;

		// Strong hand: always call truco
		if (manilhaCount >= 2) return true;

		// Decent hand + positional advantage (won a trick): call truco
		if (manilhaCount >= 1 && tricks.length >= 1) return true;

		// Partner signaled strong → bluff more confidently (team has backup)
		if (partnerStrong >= 2 && this.random() < 0.45) {
			return true; // 45% bluff rate when partner has good cards
		}

		// We know opponent is weak (intercepted NOTHING) → bluff aggressively
		if (opponentStrong < 0 && this.random() < 0.55) {
			return true; // 55% bluff rate against confirmed weak opponent
		}

		// --- TRUE BLUFFS (weak hand, strategic reasons) ---

		// Positional bluff: won trick 1, opponent doesn't know our hand strength
		const wonTrick1 = tricks.length >= 1 && tricks[0]!.winner !== null && tricks[0]!.winner === 0;
		if (wonTrick1 && highCards >= 1 && this.random() < 0.4) {
			return true;
		}

		// Desperation bluff: significantly behind on score
		if (oppScore >= myScore + 5 && this.random() < 0.3) {
			return true;
		}

		// Mild bluff: slightly behind, have at least something
		if (oppScore > myScore && highCards >= 1 && this.random() < 0.15) {
			return true;
		}

		// Pure cold bluff: very rarely, bluff with nothing (unpredictability)
		if (this.random() < 0.05) {
			return true;
		}

		return false;
	}

	/* ── Card selection ────────────────────────────────── */

	private chooseCard(
		hand: Card[],
		vira: Card,
		legalActions: Action[],
		currentTrick: Observation["currentTrick"],
		tricksPlayed: number,
	): Action {
		const cardActions = legalActions.filter(
			(a): a is Extract<Action, { type: "PLAY_CARD" }> => a.type === ActionType.PLAY_CARD,
		);
		if (cardActions.length === 0) {
			return legalActions[0]!;
		}

		const sorted = [...cardActions].sort(
			(a, b) => cardStrength(hand[a.cardIndex]!, vira) - cardStrength(hand[b.cardIndex]!, vira),
		);

		// Second to play: beat opponent's card with the weakest winning card
		if (currentTrick.firstCard !== null) {
			const opponentStrength = cardStrength(currentTrick.firstCard, vira);
			const winner = sorted.find((a) => cardStrength(hand[a.cardIndex]!, vira) > opponentStrength);
			if (winner) return winner;
			// Can't beat it — throw the weakest card
			return sorted[0]!;
		}

		// First to play
		if (tricksPlayed === 0) {
			// Trick 1: lead with strongest non-manilha to test the waters
			const nonManilhas = sorted.filter((a) => !isManilha(hand[a.cardIndex]!, vira));
			if (nonManilhas.length > 0) {
				return nonManilhas[nonManilhas.length - 1]!;
			}
			// All manilhas — play the weakest one
			return sorted[0]!;
		}

		// Trick 2+: play strongest to secure the round
		return sorted[sorted.length - 1]!;
	}
}
